name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ fromJson(matrix.target).id }}

    strategy:
      fail-fast: false

      matrix:
        target:
          - '{"id":"x86_64-pc-windows","os":"windows-2022"}'
          - '{"id":"x86_64-unknown-linux","os":"ubuntu-20.04"}'
          - '{"id":"x86_64-apple-darwin","os":"macos-11"}'

    runs-on: ${{ fromJson(matrix.target).os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Rust
        run: rustup update

      - name: Build
        run: cargo build --release

      - name: Upload zip for Windows
        uses: actions/upload-artifact@v3
        with:
          name: strdeploy-${{ fromJson(matrix.target).id }}-${{ github.sha }}.zip
          path: |
            target/release/strdeploy
            target/release/strdeploy.exe
